---
# Create Credentials in Automation Controller
- name: Create a credential (tower module)
  tower_credential:
    name: "{{ item.1.name }}"
    description: "{{ item.1.description | default(omit) }}"
    organization: "{{ item.0.name }}"
    state: "{{ tower_manage_proj_state | default('present') }}"
    kind: "{{ item.1.kind }}"
    host: "{{ item.1.host | default(omit) }}"
    become_method: "{{ item.1.become_method | default(omit) }}"
    username: "{{ item.1.secrets.username | default(omit) }}"
    password: "{{ item.1.secrets.password | default(omit) }}"
    ssh_key_data: "{{ item.1.secrets.ssh_key_data | default(omit) }}"
    ssh_key_unlock: "{{ item.1.secrets.ssh_key_unlock | default(omit) }}"
    tower_config_file: "{{ automation_controller_cli_config }}"
  loop: "{{ controller_objects.organisations | subelements('credentials', 'skip_missing = True') }}"
...