---
# Create a Inventory object in Automation Controller 
- name: " Create Inventories"
  tower_inventory:
    name: "My Created Inventory"
    description: "Created via API"
    organization: "Core"
    state: "present"
    #tower_config_file: "{{ automation_controller_cli_config }}"
    tower_host: 10.211.55.22
    tower_username: linuxadm
    tower_password: linuxadm
    validate_certs: no
  #loop: "{{ controller_objects.organisations | subelements('inventories', 'skip_missing=True') }}"
...